### ISSUE TITLE
Step by Step, please

### ISSUE THREAD

**Issue by chuchotiao** [balena-io-playground/balena-dash-photo-slideshow#3]
Hello, I'm new at this and I kinda lost.

I follow this tutorial:https://www.balena.io/blog/make-a-web-frame-with-raspberry-pi-in-30-minutes/  and now the frame is working correctly with a Google presentation, but I want to use this project for google photos.
I'm kind lost with your steps:
Clone the repository with git clone https://github.com/balena-io-playground/balena-dash-google-photos.git (Already did this)

Add your balenaCloud repository name, similar to git remote add balena username@git.balena-cloud.com:usaname/projectName.git (I'm lost here, not sure which one is my BalenaCloud repository name, also do I need to do this in the folder of the just cloned repo?)

Any step by step will be appreciated. 

Thank in advance.

**Comment by geordielad** [comment]
The instructions assume a working knowledge of git but your specific git remote add command is on the top right corner of your application page in balena cloud. Copy and paste it into the command line in your cloned app,

**Comment by dansku** [comment]
@chuchotiao, thank you for the feedback!

I am working on revamping this project, I will make a video tutorial on how to setup everything then!

Thank you

**Comment by chuchotiao** [comment]
Great news! Thanks for that! Looking forward to work on it.

**Comment by dansku** [comment]
@chuchotiao regardless, are you still having an issue setting everything up?

**Comment by chuchotiao** [comment]
I didn't try again, I was waiting for the new tutorial

**Comment by dansku** [comment]
@chuchotiao no worries then!
I would suggest you try the v3, feedback is appreciated :)

**Comment by dansku** [comment]
Hey @chuchotiao , you can follow the guys here: https://www.balena.io/blog/build-a-smart-photo-slideshow-with-balenacloud/

cheers
