### ISSUE TITLE
Ideas for enhancements

### ISSUE THREAD

**Issue by geordielad** [balena-io-playground/balena-dash-photo-slideshow#4]
Thanks you for this app! I am building a digital frame from a salvaged laptop screen. I have some ideas for enhancements that I intend to attempt. Will you entertain pull requests?

Ideas:

- It looks like the express app queries the list of photos in an album once on startup. I would like to implement a regular restart to pickup new photos. 
-  Some of my photos do not scale well due to a vertical aspect ratio. I would like to add some smarts to support portrait aspect ratios.
- The changes above might be better supported by using the Photos API. I really like the simplicity of the current implementation but some people might like a more secure implementation requiring an authorization flow. Comments from the author or other users?

**Comment by dansku** [comment]
@geordielad thanks for the feedback!
I am revamping this project, so feedback is always welcomed!
Also keep an eye on the following days/weeks as I will push some cool updates here! :)
