### ISSUE TITLE
Slideshow stops after the last picture

### ISSUE THREAD

**Issue by dontwaste** [balena-io-playground/balena-dash-photo-slideshow#6]
Hi!

I'm using an album from Google Photos and it seems the slideshow stops when it gets to the end of the album. In your previous version it kept looping the album.

**Comment by dansku** [comment]
Hey @dontwaste, which settings are you using?
Tomorrow I will spend some time improving the project and fixing any issues.

Thanks

**Comment by dontwaste** [comment]
Could you specify, which settings are you referring to? 

I pushed the upgraded version today and after a while I just get a black screen. I'm not entirely sure if it happens when the album ends. Haven't been sitting in front of the screen waiting for it to go black, but after some time it goes blank and I assume it's after the last picture in the album.

**Comment by dansku** [comment]
@dontwaste the album should restart.

I notice one issue today, what you can try doing is restart the WPE container and see if it fixes the current issue?

Quick question, how many pictures do you have in this album?

**Comment by dontwaste** [comment]
Hey, sorry it took me so long to respond, but this time I actually started a stopwatch to see how long it would run before stopping. 

When I plug it in, it comes online but the slideshow does not start, I have to restart the WPE in order for it to start the slidehow.

It ran for about 38 minutes and 40 seconds, which would mean it went through 116 (which is way less than the number of photos in the album) photos (my delay is set to 20 000), then it restarted and for some reason this time the slideshow actually started again.

On previous attempts, when it wouldn't start on its own, I think there might have been a spinning clock, but I'm not sure (I definitely have seen it at some point, but can't remember if it was there after a failed restart or not).

If the slideshow continues to run and doesn't stop again, I'm gonna close the issue.

**Comment by dontwaste** [comment]
After pretty much the same time it restarted again, but thi time, no slideshow and no spinning clock.

After restarting the wpe, it work as it should.

Would it be possible to make the wpe restart after everything else is up and running?

**Comment by dansku** [comment]
Thanks for the feedback, quick question, could you try the v3 branch?

Thanks

**Comment by dontwaste** [comment]
Thanks, tried the v3 and it seems to be working perfectly, at least it has been running for 3.5 hours now and nothing to complain.

Thanks again.

**Comment by dansku** [comment]
That is great to know. Also the v3 automatically update the feed every 12h (which you can change on the settings), so if you add or remove pictures from the album they will automatically update. There are still a couple of cosmetics updates I wanna do, but so far it seems to work :)

Anything let me know!
Thanks
