### ISSUE TITLE
backlight off?

### ISSUE THREAD

**Issue by kikamek** [balena-io-playground/balena-dash-photo-slideshow#9]
Thought I had the solution, but what is the device variable to turn the screen off during off-peak times? I have tried running the scheduler variables, but the service isnt included in this build. Any advice?

**Comment by dansku** [comment]
Hey @kikamek, I am currently testing the integration of this project with the regular balena-dash. 
Could you please test this branch https://github.com/balena-io-projects/balena-dash/tree/photos and report of it works as you desire?

Thanks :)

**Comment by kikamek** [comment]
That did it!!! Beautiful
